name: covid
channels:
  - default
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - ipython
  - ipykernel
  - notebook
  - jupyter
  - pandas
  - matplotlib
  - seaborn
  - requests
  - flake8
  - black
  - cartopy
  - geopandas>=0.7
  - descartes
