name: covid
channels:
  - default
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - ipython
  - ipykernel
  - pandas
  - lxml
  - pyarrow
  - matplotlib
  - seaborn
  - requests
  - flake8
  - black
