name: covid
channels:
  - default
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - ipython
  - ipykernel
  - notebook
  - jupyter
  - pandas>=1.0
  - matplotlib
  - seaborn
  - bokeh
  - requests
  - geopandas>=0.7
  - descartes
  - cmocean
  - ffmpeg
  - pillow
  - flake8
  - black
