= COVID-19/Coronavirus Tracker
// Doc metadata
:author: Robert Bennett
:github-profile: link:https://github.com/rben01
:github-repo: {github-profile}/covid19
:github-icon-in-link: icon:github[]{nbsp},role="no-underline"
:email: https://rben01.github.io/[Other Projects,role="underline prominent-link"] {nbsp}/{nbsp} {github-profile}[{github-icon-in-link}]{github-profile}[rben01,role="underline prominent-link"]
:description: Several graphs showing how coronavirus has spread throughout the world, individual countries, and individual USA states. The "Notes" section provides some background info and caveats for these graphs.
:keywords: coronavirus, covid, covid-19, pandemic, visualization, graph
:docinfo: shared
:favicon: ./SARS-CoV-2_favicon.png
// Formatting
:sectlinks:
:toc: left
:toc-placement: auto
:toc-title: Contents
:toclevels: 4
:hide-uri-scheme:
:stylesheet: ./styles/clean.css
:linkcss:
:icons: font
:data-table-path: data/data_table.csv
:raw-gh-content-url: link:https://raw.githubusercontent.com/rben01/covid19/master
:note-table-opts: pass:[cols=">.<1,<.<50a",frame="none",grid="none",stripes="none",options="autowidth.stretch"]
// Set up icons for GitHub and non-GitHub rendering
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:data-table-gh-link: link:{data-table-path}
:fig-dir: ./docs/figures
:note-table-opts:
:bullet-setup: 🛠
:bullet-data-source: 💾
:bullet-notes: 📓
:bullet-graphs: 📈
:bullet-world: 🌍
:bullet-countries: 🗺
:bullet-usa: 🇺🇸
:bullet-data-quality: ✅
:bullet-start-date: 📆
:bullet-doubling-time: ⏳
:bullet-top-ten: 🔟
:bullet-updates: 🔄
:bullet-cfr-notes: 📝
:bullet-gridlines: #️⃣
endif::[]
ifndef::env-github[]
:data-table-gh-link: {github-repo}/blob/master/{data-table-path}
:fig-dir: ./figures
// :icon-opts: fw
// :icon-setup: icon:gear[{icon-opts}]
// :icon-data-source: icon:table[{icon-opts}]
// :icon-notes: icon:sticky-note[{icon-opts}]
// :icon-graphs: icon:chart-line[{icon-opts}]
// :icon-world: icon:globe[{icon-opts}]
// :icon-countries: icon:globe-americas[{icon-opts}]
// :icon-usa: icon:flag-usa[{icon-opts}]
// :icon-data-quality: icon:check-circle[{icon-opts}]
// :icon-start-date: icon:calendar-day[{icon-opts}]
// :icon-doubling-time: icon:angle-double-up[{icon-opts}]
// :icon-top-ten: icon:sort-amount-up[{icon-opts}]
// :icon-updates: icon:sync-alt[{icon-opts}]
// :icon-cfr-notes: icon:notes-medical[{icon-opts}]
:bullet-opts: fw
:bullet-setup: icon:gear[{bullet-opts}]
:bullet-data-source: icon:table[{bullet-opts}]
:bullet-notes: icon:sticky-note[{bullet-opts}]
:bullet-graphs: icon:chart-line[{bullet-opts}]
:bullet-world: icon:globe[{bullet-opts}]
:bullet-countries: icon:globe-americas[{bullet-opts}]
:bullet-usa: icon:flag-usa[{bullet-opts}]
:bullet-data-quality: icon:check-circle[{bullet-opts}]
:bullet-start-date: icon:calendar-alt[{bullet-opts}]
:bullet-doubling-time: icon:stopwatch[{bullet-opts}]
:bullet-top-ten: icon:sort-amount-down[{bullet-opts}]
:bullet-updates: icon:sync-alt[{bullet-opts}]
:bullet-cfr-notes: icon:heartbeat[{bullet-opts}]
:bullet-gridlines: icon:hashtag[{bullet-opts}]
:bullet-interaction: icon:mouse[{bullet-opts}]
endif::[]
// Icons for sections
:icon-setup: 🛠
:icon-data: 💾
:icon-sources: 🚰
:icon-notes: 📓
:icon-graphs: 📊
:icon-line-graphs: 📈
:icon-interactive-timeline: ⏯
:icon-interactive-cumulative: ↗️
:icon-interactive-day-diff: ↪️
:icon-world: 🌍
:icon-countries: 🗺
:icon-usa: 🇺🇸
:icon-data-quality: ✅
:icon-start-date: 📆
:icon-doubling-time: ⏳
:icon-top-ten: 🔟
:icon-updates: 🔄
:icon-cfr-notes: 📝
:icon-reading-graphs: 📖
// Location + data labels
:over-time: over time
:world: World, China, and Rest of World
:countries: Countries
:usa-states: USA States
:cases-deaths-count-raw: Cases and deaths
:cases-deaths-per-cap: Cases and deaths per capita
:cases-deaths-raw-count: Cases and deaths {over-time}
:cases-deaths-per-cap: Cases and deaths per capita {over-time}
:cases-since-100: Cases since hitting 100 cases
:deaths-since-25: Deaths since hitting 25 deaths
:sep: {sp}-{sp}
// Directories + image descriptions
:total-count-dir: Total_cases
:per-capita-dir: Per_capita
:fixed-date-dir: From_fixed_date
:since-outbreak-dir: From_local_spread_start
:stage-all-dir: Stage_All
:stage-confirmed-dir: Stage_Confirmed
:stage-death-dir: Stage_Death
:img-world: world.png
:img-countries: countries_wo_china.png
:img-usa-states: states.png
:img-opts: width=750
:title-world-cases-deaths-over-time: {world}{sep}{cases-deaths-raw-count}
:title-countries-cases-deaths-raw-count: {countries}{sep}{cases-deaths-raw-count}
:title-countries-cases-deaths-per-capita: {countries}{sep}{cases-deaths-per-cap}
:title-countries-cases-since-100: {countries}{sep}{cases-since-100}
:title-countries-deaths-since-25: {countries}{sep}{deaths-since-25}
:title-usa-states-cases-deaths-raw-count: {usa-states}{sep}{cases-deaths-raw-count}
:title-usa-states-cases-deaths-per-capita: {usa-states}{sep}{cases-deaths-per-cap}
:title-usa-states-cases-since-100: {usa-states}{sep}{cases-since-100}
:title-usa-states-deaths-since-25: {usa-states}{sep}{deaths-since-25}
:doubling-time-explanation-cases: The thin dotted lines are annoted with a time period and show how the number of cases would grow if it doubled periodically with that period.
:doubling-time-explanation-deaths: The thin dotted lines are annoted with a time period and show how the number of deaths would grow if it doubled periodically with that period.
:insufficient-width-warning: Your device is not wide enough to display this content. Try rotating your device or viewing this site on a larger device.
:post-interactive-graph-div: pass:[<div class="mobile-vertical-spacer"></div>]

ifdef::env-github[]
__Read this page as a standalone webpage https://rben01.github.io/covid19/[here], where it is formatted much more nicely than GitHub's READMEs.__
endif::[]

[.lead]
This page contains graphs of the spread of coronavirus throughout the world and code to create those graphs.

****
While this document discusses the effects of coronavirus from a statistical standpoint, its intent is not to reduce those affected by coronavirus to mere statistic.
Unfortunately, graphs cannot exhibit the personal and societal impacts of a disaster; they can only show the numerical outcomes.
****

[[sect-setup]]
== {icon-setup} Setup

. Clone the {github-repo}[GitHub repo]:
+
[source,bash]
----
git clone https://github.com/rben01/covid19.git
cd covid19
----

. Create the conda environment:
+
--
[source,bash]
conda env create -f environment.yml

NOTE: If you do not already have `conda` installed, you can install it from https://www.anaconda.com/distribution/[here].
--

. Activate the environment:
[source,bash]
conda activate covid

. Finally, run the graphing script:
[source,bash]
python src/case_tracker.py

. The script has a command line interface; check it out:
[source,bash]
python src/case_tracker.py --help

[[sect-data]]
== {icon-data} Data

[[data-sources]]
=== {icon-sources} Sources

* https://www.washingtonpost.com/graphics/2020/world/mapping-spread-new-coronavirus/data/clean/world-daily-historical.csv[__The Washington Post__ -- world historical data] +
__The Washington Post appears to have stopped updating this dataset, so the graphs below will only have international data through approximately April 23^rd^. This issue is under investigation. U.S. states`' data comes from a different source and should be up to date.__
* https://covidtracking.com/api/states/daily.csv[The COVID Tracking Project -- US states historical data]
* https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population[Wikipedia -- List of Countries by Population]
* https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States_by_population[Wikipedia -- List of US States by Population]

In addition, while not in use, https://coronadatascraper.com/#home[Corona Data Scraper] seems like a good source as well.


[TIP]
--
The above data -- which is what's used in the graphs below -- has been aggregated into a single table available {raw-gh-content-url}/{data-table-path}[here].
Refer to <<date-explanation-note,the note below>> for the interpretation of the dates in this table.
--

[[data-notes]]
=== {icon-notes} Notes

{bullet-data-quality} Data Quality::
These graphs only convey accurate information when the data feeding them is good; https://xkcd.com/2295[garbage in, garbage out].
In particular, the number of confirmed cases in a given region is reflective of both that region's true number of cases _and_ their testing capabilities.
A rapid initial increase in confirmed cases is likely more indicative of early testing initiatives than the true rate of spread, and as the true number of true cases outpaces a region's testing capabilities, the reported number of confirmed cases will be an increasingly low estimate of the true number of cases. +
Similarly, the number of deaths attributed to COVID may fall short of the true number of deaths COVID has caused.
For instance, on April 6, 2020, New York announced that they no longer had the capacity to perform post mortem coronavirus tests, which means New Yorkers who die of COVID without having been diagnosed with COVID will not be recorded as having died from it.
This is also not to mention those who died because of coronavirus, but not _from_ it; there are many who would otherwise have received medical care but, due to the burden placed on the world's healthcare infrastructure by coronavirus or reluctance to go to a hospital because of the risk of catching coronavirus, have not been able to.
+
[example]
--
For a more in-depth picture of the difficulties of data collection vis-à-vis pandemic modeling, see FiveThirtyEight's https://fivethirtyeight.com/features/a-comic-strip-tour-of-the-wild-world-of-pandemic-modeling/[A Comic Strip Tour Of The Wild World Of Pandemic Modeling]
--

{bullet-updates} Data Updates::
Due to changing quality and up-to-dateness, the data sources used for these graphs are subject to change.
Additionally, while data sources are expected to update periodically with new, current data, they may also amend their past data as they get more accurate historical data. +
On assumption these graphs make is that the population within a region is constant over time -- any changes in a region's population are ignored when computing per-capita numbers.
This assumption is problematic.
For instance, early on, many New Yorkers left the state for elsewhere in the U.S.
If a region's true population decreases (its residents emigrate), then its per-capita numbers will be artificially deflated.
Correspondingly, if a region's true population increases (people immigrate), then its per-capita numbers will be artificially inflated.


{bullet-cfr-notes} Case Fatality Rate (CFR)::
CFR = ^deaths^/~confirmed{sp}cases~.
This is an underestimate of the true CFR within a region; how low of an estimate it is depends on how quickly the rate of new confirmed cases is increasing relative to existing confirmed cases (the slopes of the lines in the below plots).
If the infection rate increases rapidly, the computed CFR will be a gross underestimate, as new infections won't yet have had time to become fatal.
If it's been flat for a while, then the computed CFR should approach the true CFR, as cases will all be resolved (either fatally or not). +
Of course, the numerator and denominator may be inaccurate to do testing issues.
And the true CFR within a region can itself change over time as treatment quality goes up (e.g., more resources per capita allocated to response) or down (e.g., hospitals become overburdened).

[[sect-graphs]]
== {icon-graphs} Graphs

[[graphs-timeline-interactive-us]]
=== {icon-interactive-timeline} Interactive Trackers

This section contains two pairs of interactive 2x2 grid-plots: one pair for the continental U.S. and one pair for the world's countries (due to data issues, a handful of countries are not present).
All four grid-plots have four quadrants showing how the number of cases and deaths, total and per capita, has progressed over time.
In each pair, the first grid-plot shows these numbers cumulatively and the second grid-plot shows how these numbers increased each day.
For instance, New York had 6 cases on March 4 and 22 on March 5; the top-left quadrant of the first U.S. grid-plot would show 22 for New York on March 5, while that of the second grid-plot would show 16 (22 minus 6). +
Regions that are light gray on a given day had no cases/deaths that day.
Otherwise, the colors are logarithmically scaled.
Each pair of major ticks has eight minor ticks between them (ten including the major ticks), which means the minor ticks between a×b^n^ and a×b^n+1^ are located at a×b^n^(bk-k+9)/9 for k=1, 2, ..., 7, 8.
Because the range of values in each quadrants is different, each quadrant's color scale is unique to that quadrant. +
On desktop, zoom by holding the shift key and scrolling over the graph.
Once you've zoomed in, you can drag to pan and can reset the view by double-clicking on the graph.
On mobile, use two fingers to zoom and pan.
Hovering your cursor over a region (desktop) or tapping it (mobile) will show its data for the selected date.
Along the bottoms are controls for continuous playback of the data over time as well as a slider to pick the date manually.

++++
<div id="map-plots"></div>
++++


[[graphs-line]]
=== {icon-line-graphs} Line Charts

[[sect-reading-graphs]]
==== {icon-reading-graphs} Reading the Line Chart

[[date-explanation-note]]{bullet-start-date} Interpreting the Axes::
The dates on the graphs`' x-axes represent data collected in the time span from the most recent occurrence of midnight to the given date.
For instance, the vertical line over March 21 represents data collected from 00:00 March 20 to 23:59:59 March 20.
On the last day, there will be less than 24 hours of collected data, so the vertical line over `today` at `current time` represents the data collected from midnight (this morning) to now.
+
The y-axis of the graphs is log scaled.
On all graphs, minor y-axis gridlines are spaced linearly between major gridlines.

{bullet-top-ten} Ranking and Sorting::
In each graph, the "`top 10`" locations for the given variable are displayed. You can use the arrows to move to lower- or higher-ranked locations (not yet implemented; coming soon).

{bullet-interaction} Interaction::
By default, the legend displays data for the graphed locations on the most recent date for which there is data. Hover your mouse over the graph to choose a different date to display in the legend.

++++
<div id="line-charts-section"></div>
++++
