= COVID-19/Coronavirus Tracker
:author: Robert Bennett
:github-profile: https://github.com/rben01
:github-repo: {github-profile}/covid19
:email: {github-profile}[GitHub Profile]
:description: Several graphs showing how coronavirus has spread throughout the world, individual countries, and individual USA states. The "Notes" section provides some background info and caveats for these graphs.
:keywords: coronavirus, covid, covid-19, pandemic, visualization, graph
:hide-uri-scheme:
:favicon: ./SARS-CoV-2_favicon.png
:sectlinks:
:toc: left
:toc-placement: auto
:toc-title: Contents
:toclevels: 4
:over-time: over time
:stylesheet: ./styles/clean.css
:linkcss!:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:data-table-source: link:data/data_table.csv
:fig-dir: ./docs/figures
endif::[]
ifndef::env-github[]
:data-table-source: {github-repo}/blob/master/data/data_table.csv
:fig-dir: ./figures
endif::[]
:world: World, China, and Rest of World
:countries: Countries
:usa-states: USA States
:cases-deaths-count-raw: Cases and deaths
:cases-deaths-per-cap: Cases and deaths per capita
:cases-deaths-count-raw-over-time: Cases and deaths {over-time}
:cases-deaths-per-cap-over-time: Cases and deaths per capita {over-time}
:cases-since-100: Cases since hitting 100 cases
:deaths-since-25: Deaths since hitting 25 deaths
:sep: {sp}-{sp}
:total-count-dir: Total_cases
:per-capita-dir: Per_capita
:fixed-date-dir: From_fixed_date
:since-outbreak-dir: From_local_spread_start
:stage-all-dir: Stage_All
:stage-confirmed-dir: Stage_Confirmed
:stage-death-dir: Stage_Death
:img-world: world.png
:img-countries: countries_wo_china.png
:img-usa-states: states.png
:img-opts: width=750
:title-world-cases-deaths-over-time: {world}{sep}{cases-deaths-count-raw-over-time}
:title-countries-cases-deaths-count-raw-over-time: {countries}{sep}{cases-deaths-count-raw-over-time}
:title-countries-cases-deaths-per-capita: {countries}{sep}{cases-deaths-per-cap-over-time}
:title-countries-cases-since-100: {countries}{sep}{cases-since-100}
:title-countries-deaths-since-25: {countries}{sep}{deaths-since-25}
:title-usa-states-cases-deaths-count-raw-over-time: {usa-states}{sep}{cases-deaths-count-raw-over-time}
:title-usa-states-cases-deaths-per-capita: {usa-states}{sep}{cases-deaths-per-cap-over-time}
:title-usa-states-cases-since-100: {usa-states}{sep}{cases-since-100}
:title-usa-states-deaths-since-25: {usa-states}{sep}{deaths-since-25}

ifndef::env-github[]
[pass]
++++
<style>
body { font-family: sans-serif !important; }
</style>
++++
endif::[]


[.lead]
This page contains graphs of the spread of coronavirus throughout the world and code to create those graphs.

ifdef::env-github[]
__Read this page as a standalone webpage https://rben01.github.io/covid19/[here].__
endif::[]



// '''

// toc::[]

// '''

[[sect-setup]]
== 🛠 Setup

. Clone the {github-repo}[GitHub repo]
+
[bash]
----
git clone https://github.com/rben01/covid19.git
cd covid19
----

. Create the conda environment using
+
--
[source,bash]
conda env create -f environment.yml

NOTE: If you do not already have `conda` installed, you can install it from https://www.anaconda.com/distribution/[here].
--

. Activate the environment with
[source,bash]
conda activate covid

. Finally, run the graphing script
[source,bash]
python src/case_tracker.py

. The script has a command line interface; check it out with
[source,bash]
python src/case_tracker.py --help

[[sect-data-sources]]
== 💾 Data Sources


* https://www.washingtonpost.com/graphics/2020/world/mapping-spread-new-coronavirus/data/clean/world-daily-historical.csv[Washington Post world historical data]
* https://covidtracking.com/api/states/daily.csv[covidtracking.com US states historical data]
* https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population[Wikipedia - List of Countries by Population]
* https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States_by_population[Wikipedia - List of US States by Population]


****
https://coronadatascraper.com/#home[Corona Data Scraper] is not currently used, but it seems decent as well. +
****

TIP: The data used to create these graphs is available {data-table-source}[here].

[[sect-notes]]
== 📓 Notes
****
While this document discusses the effects of coronavirus from a statistical standpoint, its intent is not to reduce those affected by coronavirus to mere statistics. Unfortunately, graphs cannot exhibit the personal and societal impacts of a disaster; they can only show the numerical outcomes. It is with this mindset that this document was written.
****

[options="compact"]
* ✅ These graphs only convey accurate information when the data feeding them is good; garbage in, garbage out. In particular, as the number of (true) cases grows and regions lose the ability to test everyone infected, the reported number of confirmed cases will be an increasingly low estimate of the true number of cases. +
Similarly, the number of deaths attributed to COVID may fall short of the true number of deaths COVID has caused. For instance, on April 6, 2020, New York announced that they no longer had the capacity to perform post mortem coronavirus tests, which means New Yorkers who die of COVID without having been diagnosed with COVID will not be recorded as having died from it. +
This is also not to mention those who died because of coronavirus, but not _from_ it; there are many who would otherwise have received medical care but, due to the burden placed on the world's healthcare infrastructure by coronavirus, have not been able to.
* 📅 In all graphs below, the start date was the earliest date for which there was data available and for which any of the plotted locations had confirmed cases.
* ⏳ Some graphs are annotated with benchmark lines showing the rate of new cases (possibly per capita) for a particular doubling time (or "DT" for short). Lines annotated "n days" show how the number of coronavirus cases would increase within a region if it doubled every n days. Comparing the slope of a region's growth line to the slopes of these benchmark lines gives an indication of that region's doubling time. These graphs' legends also list the doubling times over different periods of time (e.g., "20d DT" means the average doubling time of a region over the past 20 days"). +
To find the daily percent increase for any doubling time T, simply compute 2^1/T^. Below is a list of doubling times and corresponding per-day percent increases.
** 1 day: +100% daily
** 2 days: +41% daily
** 3 days: +26% daily
** 4 days: +19% daily
** 5 days: +15% daily
** 6 days: +12% daily
** 1 week: +10% daily
** 2 weeks: +5% daily
* 🔟 In each graph, the "top 10" refers to top 10 by number of cases, even for the graphs of cases per capita. Graphs' legends are, however, sorted according to the relevant measurement (number of cases, cases per capita, or doubling time thereof). +
For example, in a graph of countries and their cases per capita, the first country in the legend will have the most cases per capita of all countries included in that graph, but not necessarily the most cases per capita of any country in the world (the country with the most cases per capita in the world — San Marino at the time of writing — would have to be in the top 10 by number of cases to make it onto the graph, which it's obviously not given its population of 33k).
* 🔄 Due to changing quality and up-to-dateness, the data sources used for these graphs are subject to change. Additionally, while data sources are expected to update periodically with new, current data, they may also amend their past data as they get more accurate historical data.

* 📝 Case Fatality Rate (CFR) notes

** CFR = Case fatality rate = deaths / confirmed.
** This is an underestimate of the true CFR within a region; how low of an estimate it is depends on how quickly the rate of new confirmed cases relative to existing confirmed cases (the slopes of the lines in the below log-scaled plots) is increasing. If the infection rate increases rapidly, the computed CFR will be a gross underestimate, as new infections won't yet have had time to become fatal. If it's been flat for a while, then the computed CFR should approach the true CFR, as cases will all be resolved (either fatally or not). +
Of course, the numerator and denominator may themselves be inaccurate to do testing issues. And the true CFR within a region can itself change over time as treatment quality goes up (e.g., more resources per capita allocated to response) or down (e.g., hospitals become overburdened).
** The nature of log-scale graphs is that the CFR can be observed from the vertical distance between the *Confirmed Cases* and *Deaths* lines for a given country — the larger the distance, the lower the CFR. (The computed CFR is roughly 1/2^distance^; again this will be an underestimate.)

[[sect-graphs]]
== 📈 Graphs

[[graphs-world-china-row]]
=== 🌍 {world}

[[world-china-row-cases-deaths]]
==== {title-world-cases-deaths-over-time}

image:{fig-dir}/{total-count-dir}/{fixed-date-dir}/{stage-all-dir}/{img-world}["{title-world-cases-deaths-over-time}",{img-opts},title="{title-world-cases-deaths-over-time}"]

[[graphs-top-ten-countries-no-china]]
=== 🗺 Top Ten Countries, Excluding China

[[top-ten-countries-no-china-cases-deaths-total]]
==== {title-countries-cases-deaths-count-raw-over-time}

image:{fig-dir}/{total-count-dir}/{fixed-date-dir}/{stage-all-dir}/{img-countries}["{title-countries-cases-deaths-count-raw-over-time}",{img-opts},title="{title-countries-cases-deaths-count-raw-over-time}"]

[[top-ten-countries-no-china-cases-deaths-per-capita]]
==== {title-countries-cases-deaths-per-capita}

image:{fig-dir}/{per-capita-dir}/{fixed-date-dir}/{stage-all-dir}/{img-countries}["{title-countries-cases-deaths-per-capita}",{img-opts},title="{title-countries-cases-deaths-per-capita}"]

[[top-ten-countries-no-china-cases-since]]
==== {title-countries-cases-since-100}

image:{fig-dir}/{total-count-dir}/{since-outbreak-dir}/{stage-confirmed-dir}/{img-countries}["{title-countries-cases-since-100}",{img-opts},title="{title-countries-cases-since-100}"]

[[top-ten-countries-no-china-deaths-since]]
==== {title-countries-deaths-since-25}

image:{fig-dir}/{total-count-dir}/{since-outbreak-dir}/{stage-death-dir}/{img-countries}["{title-countries-deaths-since-25}",{img-opts},title="{title-countries-deaths-since-25}"]


[[graphs-usa-top-states]]
=== 🇺🇸 Top Ten USA States

[[usa-top-states-cases-deaths-total]]
==== {title-usa-states-cases-deaths-count-raw-over-time}

image:{fig-dir}/{total-count-dir}/{fixed-date-dir}/{stage-all-dir}/{img-usa-states}["{title-usa-states-cases-deaths-count-raw-over-time}",{img-opts},title="{title-usa-states-cases-deaths-count-raw-over-time}"]

[[usa-top-states-cases-deaths-per-capita]]
==== {title-usa-states-cases-deaths-per-capita}

image:{fig-dir}/{per-capita-dir}/{fixed-date-dir}/{stage-all-dir}/{img-usa-states}[{title-countries-cases-deaths-per-capita},{img-opts},title="{title-usa-states-cases-deaths-per-capita}"]

[[usa-top-states-cases-since]]
==== {title-usa-states-cases-since-100}

image:{fig-dir}/{total-count-dir}/{since-outbreak-dir}/{stage-confirmed-dir}/{img-usa-states}["{title-countries-cases-since-100}",{img-opts},title="{title-usa-states-cases-since-100}"]

[[usa-top-states-deaths-since]]
==== {title-countries-deaths-since-25}

image:{fig-dir}/{total-count-dir}/{since-outbreak-dir}/{stage-death-dir}/{img-usa-states}["{title-usa-states-deaths-since-25}",{img-opts},title="{title-usa-states-deaths-since-25}"]
